backend:
  name: github
  repo: wen00033/new-blog
  branch: master
  squash_merges: true
  open_authoring: false

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://master--benjamin-works-webiste.netlify.app"

collections:
  - name: post
    label: Posts
    folder: src/pages/blog
    create: true
    format: frontmatter
    # preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
