backend:
  name: github
  repo: wen00033/new-blog #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://app.netlify.com/sites/benjamin-works-webiste"
